use crate::codegen::rust::RustGeneratorError;
use crate::codegen::rust::functions::generate_function;
use crate::codegen::rust::structs::generate_struct;
use crate::codegen::rust::utils::{add_vinculum_mod, get_cargo_manifest_path};
use crate::codegen::types::{FfiLangType, File};
use std::fs;

pub fn generate_files<T>(
    files: Vec<File<T>>,
    language: &'static str,
) -> Result<(), RustGeneratorError>
where
    T: FfiLangType,
{
    let manifest_dir = get_cargo_manifest_path()?;
    let src_path = manifest_dir.join("src");

    add_vinculum_mod(&src_path)?;

    let vinculum_path = manifest_dir.join("vinculum");
    let language_path = manifest_dir.join(language);

    let vinculum_module_path = vinculum_path.join("mod.rs");
    let language_module_path = language_path.join("mod.rs");

    let mut vinculum_module_content = String::new();
    vinculum_module_content.push_str("// This file is auto-generated by build.rs\n");
    vinculum_module_content
        .push_str("// Do not edit manually - changes will be overwritten during build\n\n");
    vinculum_module_content.push_str("pub mod ");
    vinculum_module_content.push_str(language);
    let mut language_module_content = String::new();
    language_module_content.push_str("// This file is auto-generated by build.rs\n");
    language_module_content
        .push_str("// Do not edit manually - changes will be overwritten during build\n\n");

    for File {
        name,
        structs,
        functions,
    } in files
    {
        vinculum_module_content.push_str("pub mod ");
        vinculum_module_content.push_str(name.as_str());
        vinculum_module_content.push('\n');

        let mut content = String::new();
        content.push_str("// This file is auto-generated by build.rs\n");
        content.push_str("// Do not edit manually - changes will be overwritten during build\n\n");
        content.push_str("use vinculum_main::ffi::call::call_haskell_typed;\n"); // TODO
        content.push_str("#[allow(unused_imports)]\n");
        content.push_str("use vinculum_main::ffi::value::{AcceptedTypes, Value};\n\n"); // TODO

        for s in structs {
            generate_struct(s, &mut content);
            content.push_str("\n\n");
        }

        for f in functions {
            generate_function(f, &mut content, &name);
            content.push_str("\n\n");
        }

        let file_path = vinculum_path.join(format!("{}.rs", name));
        fs::write(&file_path, content).map_err(|e| {
            crate::codegen::rust::errors::RustGeneratorError::FileOperation(e.to_string())
        })?;
    }

    fs::write(&vinculum_module_path, vinculum_module_content).map_err(|e| {
        crate::codegen::rust::errors::RustGeneratorError::FileOperation(e.to_string())
    })?;
    fs::write(&language_module_path, language_module_content).map_err(|e| {
        crate::codegen::rust::errors::RustGeneratorError::FileOperation(e.to_string())
    })?;

    Ok(())
}
