use crate::build_scripts::parser::Function;
use crate::build_scripts::utils::helpers::to_snake_case;

use std::path::PathBuf;
use std::{env, fs};

pub(crate) fn generate_functions_with_modules(file_modules: &[(String, Vec<Function>)]) {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"));
    let dest = manifest_dir.join("src").join("functions.rs");

    let mut code = String::new();
    code.push_str("// This file is auto-generated by build.rs\n");
    code.push_str("// Do not edit manually - changes will be overwritten during build\n\n");

    for (module_name, functions) in file_modules {
        let rust_module_name = to_snake_case(module_name);

        code.push_str(&format!("pub mod {} {{\n", rust_module_name));
        code.push_str("    use crate::ffi::call::call_haskell_typed;\n");
        code.push_str("    use crate::ffi::value::{AcceptedTypes, Value};\n\n");

        for function in functions {
            code.push_str("    ");
            code.push_str(&generate_function(function, module_name).replace('\n', "\n    "));
            code.push('\n');
            code.push('\n');
        }

        code.push_str("}\n\n");
    }

    fs::write(&dest, code).expect("Failed to write generated Rust bindings");
}

fn generate_function(function: &Function, module_name: &str) -> String {
    let args_sig = function
        .args
        .iter()
        .map(|arg| format!("{}: {}", arg.name, arg.r#type.rust_name()))
        .collect::<Vec<_>>()
        .join(", ");

    let args_values = function
        .args
        .iter()
        .map(|arg| arg.r#type.to_rust_value(&arg.name))
        .collect::<Vec<_>>()
        .join(", ");

    let generics = if function.generics.is_empty() {
        "".to_string()
    } else {
        format!(
            "<{}: 'static + AcceptedTypes>",
            function.generics.join(": Any + Clone + 'static, ")
        )
        .trim_start_matches(", ")
        .into()
    };
    let return_type = function.r#return.rust_name();
    let qualified_name = format!("{}_{}", to_snake_case(module_name), function.name);
    let description_comments = function
        .description
        .iter()
        .map(|desc| format!("/// {}", desc))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "{}#[allow(non_snake_case, unused_variables, unused_qualifications, dead_code)]
pub fn {name}{generics}({args_sig}) -> {return_type} {{
    call_haskell_typed(\"{qualified_name}\", &[{args_values}])
        .{conversion}.expect(\"internal FFI type error: invalid return type\")
}}",
        if description_comments.is_empty() {
            String::new()
        } else {
            format!("{}\n", description_comments)
        },
        name = function.name,
        generics = generics,
        args_sig = args_sig,
        return_type = return_type,
        qualified_name = qualified_name,
        args_values = args_values,
        conversion = if function.r#return.is_generic() {
            "into_generic()"
        } else {
            "try_into()"
        },
    )
}
