use crate::codec::Value;

/// Marker trait for codec supported by a Vinculum FFI backend.
///
/// [`Value`] defines the full set of value kinds available in the Vinculum
/// abstraction, but a given backend may only support a subset of them.
///
/// Backend-specific modules or language crates must mark supported codec
/// using the provided `accepted_*` macros.
///
/// Any type that does not implement `AcceptedTypes` is considered unsupported
/// by that backend, even if it exists in [`Value`].
///
/// This trait is intentionally empty and only serves as a compile-time filter
/// for backend-supported codec.
///
/// # Usage
///
/// Use the provided macros instead of implementing this trait manually:
///
/// ```rust,ignore
/// use vinculum_main::*;
///
/// accepted_i64!();
/// accepted_string!();
/// accepted_bool!();
/// ```
///
/// Each macro automatically:
/// - marks the type as accepted for the backend
/// - implements the corresponding [`ToValue`] conversion
///
/// This ensures consistency and avoids manual implementation errors.
pub trait AcceptedTypes: Sized {}

/// Conversion trait from a Rust value into a [`Value`] compatible with a given backend.
///
/// This trait defines how a type implementing [`AcceptedTypes`] is transformed into
/// its corresponding [`Value`] representation for a specific backend `T`.
///
/// Implementations of this trait are automatically generated by the `accepted_*`
/// macros and should not be written manually.
///
/// # Usage
///
/// ```rust,ignore
/// use vinculum_main::*;
///
/// accepted_i64!();
///
/// let x = 42i64;
/// let v = x.to_value::<MyBackend>();
/// ```
///
/// # Design
///
/// - `AcceptedTypes` → compile-time filter (what is allowed)
/// - `ToValue` → conversion logic (how it is encoded)
///
/// This separation allows:
/// - strict compile-time validation of supported codec
/// - zero-cost conversions
/// - consistent behavior across backends
///
/// # Lifetimes
///
/// The returned [`Value`] may borrow from `self`, which is why the method
/// takes `&'a self` and returns `Value<'a, T>`.
///
/// This enables zero-copy support for borrowed data such as `&str`, `&[u8]`,
/// or `&CStr`.
pub trait ToValue<T: AcceptedTypes>: Sized {
    fn to_value(&'_ self) -> Value<'_, T>;
}

#[macro_export]
macro_rules! accepted_null {
    () => {
        impl AcceptedTypes for vinculum_main::codec::Null {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for vinculum_main::codec::Null {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Null
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_unit {
    () => {
        impl AcceptedTypes for () {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for () {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Unit
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_bool {
    () => {
        impl AcceptedTypes for bool {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for bool {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Bool(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_char {
    () => {
        impl AcceptedTypes for char {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for char {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Char(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_i8 {
    () => {
        impl AcceptedTypes for i8 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for i8 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Int8(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_i16 {
    () => {
        impl AcceptedTypes for i16 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for i16 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Int16(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_i32 {
    () => {
        impl AcceptedTypes for i32 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for i32 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Int32(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_i64 {
    () => {
        impl AcceptedTypes for i64 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for i64 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Int64(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_i128 {
    () => {
        impl AcceptedTypes for i128 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for i128 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Int128(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_isize {
    () => {
        impl AcceptedTypes for isize {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for isize {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Isize(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_u8 {
    () => {
        impl AcceptedTypes for u8 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for u8 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::U8(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_u16 {
    () => {
        impl AcceptedTypes for u16 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for u16 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::U16(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_u32 {
    () => {
        impl AcceptedTypes for u32 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for u32 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::U32(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_u64 {
    () => {
        impl AcceptedTypes for u64 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for u64 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::U64(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_u128 {
    () => {
        impl AcceptedTypes for u128 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for u128 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::U128(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_usize {
    () => {
        impl AcceptedTypes for usize {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for usize {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Usize(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_f32 {
    () => {
        impl AcceptedTypes for f32 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for f32 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Float32(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_f64 {
    () => {
        impl AcceptedTypes for f64 {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for f64 {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Float64(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_str {
    () => {
        impl AcceptedTypes for &'static str {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for &'a str {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Str(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_string {
    () => {
        impl AcceptedTypes for String {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for String {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::String(self.clone())
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_cstr {
    () => {
        impl AcceptedTypes for &'static std::ffi::CStr {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for &'a std::ffi::CStr {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::CStr(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_cstring {
    () => {
        impl AcceptedTypes for std::ffi::CString {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for std::ffi::CString {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::CString(self.clone())
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_bytes {
    () => {
        impl AcceptedTypes for &'static [u8] {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for &'a [u8] {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Bytes(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_bytevec {
    () => {
        impl AcceptedTypes for std::vec::Vec<u8> {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for std::vec::Vec<u8> {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::ByteVec(self.clone())
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_ptr {
    () => {
        impl AcceptedTypes for *const std::ffi::c_void {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for *const std::ffi::c_void {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Ptr(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_mut_ptr {
    () => {
        impl AcceptedTypes for *mut std::ffi::c_void {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for *mut std::ffi::c_void {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::MutPtr(*self)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_handle {
    () => {
        impl AcceptedTypes for vinculum_main::codec::Handle {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for vinculum_main::codec::Handle {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Handle(self.0)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_fn_ptr {
    () => {
        impl AcceptedTypes for vinculum_main::codec::FnPtr {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for vinculum_main::codec::FnPtr {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::FnPtr(self.0)
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_array {
    () => {
        impl<'a, T: AcceptedTypes> AcceptedTypes for vinculum_main::codec::Array<'a, T> {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for vinculum_main::codec::Array<'a, T> {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Array(self.0.clone())
            }
        }
    };
}

#[macro_export]
macro_rules! accepted_tuple {
    () => {
        impl<'a, T: AcceptedTypes> AcceptedTypes for vinculum_main::codec::Tuple<'a, T> {}

        impl<'a, T: AcceptedTypes> ToValue<'a, T> for vinculum_main::codec::Tuple<'a, T> {
            fn to_value(&'a self) -> vinculum_main::codec::Value<'a, T> {
                vinculum_main::codec::Value::Tuple(self.0.clone())
            }
        }
    };
}
